# Generated by Django 5.1.7 on 2025-03-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='status',
            field=models.CharField(default='processing', max_length=20, verbose_name=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')]),
        ),
    ]
