# Generated by Django 5.1.7 on 2025-03-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_attachment_extracted_text_attachment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='batch_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
