# Generated by Django 5.1.7 on 2025-03-20 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_attachment_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
